var groups = {
  qbs: [
    'Aaron Rodgers',
    'Tom Brady',
    'Drew Brees',
    'Peyton Manning',
    'Andrew Luck',
    'Ben Roethlisberger',
    'Tony Romo',
    'Philip Rivers',
    'Matt Ryan',
    'Russell Wilson',
    'Cam Newton',
    'Eli Manning',
    'Matthew Stafford',
    'Joe Flacco',
    'Ryan Tannehill',
    'Sam Bradford',
    'Colin Kaepernick',
    'Jay Cutler',
    'Carson Palmer',
    'Alex Smith',
    'Teddy Bridgewater',
    'Kirk Cousins',
    'Tyrod Taylor',
    'Ryan Fitzpatrick',
    'Andy Dalton',
  ],
  presidents: [
    'George Washington',
    'John Adams',
    'Thomas Jefferson',
    'James Madison',
    'James Monroe',
    'John Quincy Adams',
    'Andrew Jackson',
    'Martin Van Buren',
    'William Henry Harrison',
    'John Tyler',
    'James K. Polk',
    'Zachary Taylor',
    'Millard Fillmore',
    'Franklin Pierce',
    'James Buchanan',
    'Abraham Lincoln',
    'Andrew Johnson',
    'Ulysses S. Grant',
    'Rutherford B. Hayes',
    'James A. Garfield',
    'Chester Arthur',
    'Grover Cleveland',
    'Benjamin Harrison',
    'William McKinley',
    'Theodore Roosevelt',
    'William Howard Taft',
    'Woodrow Wilson',
    'Warren G. Harding',
    'Calvin Coolidge',
    'Herbert Hoover',
    'Franklin D. Roosevelt',
    'Harry S. Truman',
    'Dwight D. Eisenhower',
    'John F. Kennedy',
    'Lyndon B. Johnson',
    'Richard Nixon',
    'Gerald Ford',
    'Jimmy Carter',
    'Ronald Reagan',
    'George H.W. Bush',
    'Bill Clinton',
    'George W. Bush',
    'Barack Obama'
    ]
};

module.exports = groups;
